#ifndef ConstantSSLServer_hpp
#define ConstantSSLServer_hpp

#define CONFIG_FILE "config.xml"

#define UUID_SIZE 36

#define TMP_BUFFER_SIZE 4096*4

#define TIMEOUT_FD_MAX_READ_ERROR_COUNT 50

#define SSL_HANDSHAKE_RETRY_COUNT 30
#define SSL_HANDSHAKE_RETRY_SLEEP_INTERVAL_MSEC 100

#define PROXY_CMD_NEW_CONNECTION "[SYS_Connection_NEW]"
#define PROXY_CMD_CLOSE_CONNECTION "[SYS_Connection_CLOSE]"
#define PROXY_CMD_KEEPALIVE "[SYS_Connection_KEEPALIVE]"

//#define SOCKET_IDLE_TIMEOUT_SEC 180
#define SSLSOCKET_KEEPALIVE_PACKAGE_INTERVAL_SEC 60
#define CLIENT_REKEY_INTERVAL_SEC 3600
#define SERVER_IDLE_INTERVAL_SEC 180
#define SERVER_WAIT_CONNECTION_SLEEP_INTERVAL_MSEC 100
#define ERROR_SLEEP_INTERVAL_MSEC 100
#define SSL_SOCKET_SEND_TIMEOUT_SEC 120

#define PAYLOAD_MARKER_PREFIX "<SYS_DATA_PROXY_v01_DATA_START_TAG>"
#define PAYLOAD_MARKER_POSTFIX "</SYS_DATA_PROXY_v01_DATA_END_TAG>"

#define LOG_LEVEL 150

#define OPENSSL_OPENSC_ENGINE_PKCS11_LIBRARY "OPENSSL_OPENSC_ENGINE_PKCS11_LIBRARY-NOTFOUND"
#define OPENSC_ENGINE_PKCS11_LIBRARY "OPENSC_ENGINE_PKCS11_LIBRARY-NOTFOUND"

#endif
